services:
  api:
    build: .
    container_name: orders-api
    environment:
      NODE_ENV: local
      DB_TYPE: postgres
      DB_URL: postgres
      DB_PORT: 5432
      DB_NAME: orders
      DB_USER: orders-api
      DB_PASS: orders-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - api-network
  postgres:
    restart: unless-stopped
    image: postgres:17.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: orders-api
      POSTGRES_PASSWORD: orders-api
      POSTGRES_DB: orders
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
