services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: orders-api
      POSTGRES_PASSWORD: orders-api
      POSTGRES_DB: orders
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
